package com.greenops.agent.application.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {
    BUSINESS_ERROR(HttpStatus.BAD_REQUEST),
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
    INVALID_ARGUMENT(HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED(HttpStatus.FORBIDDEN),
    COMPANY_REQUIRED(HttpStatus.BAD_REQUEST),
    COMPANY_NOT_FOUND(HttpStatus.NOT_FOUND),
    COMPANY_INACTIVE(HttpStatus.FORBIDDEN),
    MEMBERSHIP_NOT_FOUND(HttpStatus.FORBIDDEN),
    MEMBERSHIP_INACTIVE(HttpStatus.FORBIDDEN),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    USER_INACTIVE(HttpStatus.FORBIDDEN),
    USER_NOT_IN_COMPANY(HttpStatus.NOT_FOUND),
    USER_ALREADY_IN_COMPANY(HttpStatus.CONFLICT),
    USER_COMPANY_INACTIVE(HttpStatus.FORBIDDEN),
    ROLE_NOT_FOUND(HttpStatus.NOT_FOUND),
    ROLE_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    ROLE_NOT_BELONG_TO_COMPANY(HttpStatus.FORBIDDEN),
    SYSTEM_ROLE_CANNOT_BE_MODIFIED(HttpStatus.FORBIDDEN),
    ROLE_IS_IN_USE(HttpStatus.CONFLICT),
    PERMISSION_NOT_FOUND(HttpStatus.NOT_FOUND),
    PERMISSION_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    PERMISSION_SIGNATURE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    MODULE_NOT_FOUND(HttpStatus.NOT_FOUND),
    MODULE_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    RESOURCE_IN_USE(HttpStatus.CONFLICT),
    DATA_INTEGRITY_CONFLICT(HttpStatus.CONFLICT),
    INVALID_EFFECTIVE_TIME(HttpStatus.BAD_REQUEST),
    COMPANY_CONTEXT_REQUIRED(HttpStatus.BAD_REQUEST),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus status;
}
