package com.greenops.agent.domain.iam;

import org.springframework.data.domain.Page;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;
import java.util.UUID;

@Repository
public interface UserCompanyRoleRepository extends JpaRepository<UserCompanyRole, UUID> {
    @Query("SELECT assignment FROM UserCompanyRole assignment JOIN FETCH assignment.role WHERE assignment.userCompany.id = :userCompanyId")
    List<UserCompanyRole> findByUserCompanyId(@Param("userCompanyId") UUID userCompanyId);
    @Query("SELECT CASE WHEN COUNT(assignment) > 0 THEN true ELSE false END FROM UserCompanyRole assignment JOIN assignment.userCompany membership JOIN assignment.role role WHERE role.id = :roleId AND membership.company.id = :companyId AND assignment.status = com.greenops.agent.domain.iam.Status.ACTIVE")
    boolean existsActiveByRole(@Param("roleId") UUID roleId, @Param("companyId") UUID companyId);
    @Query(value = "SELECT assignment FROM UserCompanyRole assignment JOIN FETCH assignment.userCompany membership JOIN FETCH membership.user user JOIN assignment.role role WHERE role.id = :roleId AND membership.company.id = :companyId AND LOWER(user.status) = 'active' AND membership.deletedAt IS NULL AND membership.status = com.greenops.agent.domain.iam.MembershipStatus.ACTIVE AND (membership.effectiveFrom IS NULL OR membership.effectiveFrom <= :at) AND (membership.effectiveTo IS NULL OR membership.effectiveTo > :at) AND assignment.status = com.greenops.agent.domain.iam.Status.ACTIVE AND (assignment.effectiveFrom IS NULL OR assignment.effectiveFrom <= :at) AND (assignment.effectiveTo IS NULL OR assignment.effectiveTo > :at)", countQuery = "SELECT count(assignment) FROM UserCompanyRole assignment JOIN assignment.userCompany membership JOIN membership.user user JOIN assignment.role role WHERE role.id = :roleId AND membership.company.id = :companyId AND LOWER(user.status) = 'active' AND membership.deletedAt IS NULL AND membership.status = com.greenops.agent.domain.iam.MembershipStatus.ACTIVE AND (membership.effectiveFrom IS NULL OR membership.effectiveFrom <= :at) AND (membership.effectiveTo IS NULL OR membership.effectiveTo > :at) AND assignment.status = com.greenops.agent.domain.iam.Status.ACTIVE AND (assignment.effectiveFrom IS NULL OR assignment.effectiveFrom <= :at) AND (assignment.effectiveTo IS NULL OR assignment.effectiveTo > :at)")
    Page<UserCompanyRole> findEffectiveUsersByRole(@Param("roleId") UUID roleId, @Param("companyId") UUID companyId, @Param("at") LocalDateTime at, org.springframework.data.domain.Pageable pageable);
    @Query("SELECT CASE WHEN COUNT(assignment) > 0 THEN true ELSE false END FROM UserCompanyRole assignment JOIN assignment.userCompany membership JOIN assignment.role role WHERE membership.user.id = :userId AND LOWER(membership.user.status) = 'active' AND membership.company.id = :companyId AND membership.deletedAt IS NULL AND membership.status = com.greenops.agent.domain.iam.MembershipStatus.ACTIVE AND (membership.effectiveFrom IS NULL OR membership.effectiveFrom <= :at) AND (membership.effectiveTo IS NULL OR membership.effectiveTo > :at) AND assignment.status = com.greenops.agent.domain.iam.Status.ACTIVE AND (assignment.effectiveFrom IS NULL OR assignment.effectiveFrom <= :at) AND (assignment.effectiveTo IS NULL OR assignment.effectiveTo > :at) AND role.scope = com.greenops.agent.domain.iam.RoleScope.SYSTEM AND role.code = :roleCode AND role.status = com.greenops.agent.domain.iam.Status.ACTIVE AND role.deletedAt IS NULL")
    boolean hasEffectiveSystemRole(@Param("userId") UUID userId, @Param("companyId") UUID companyId, @Param("roleCode") String roleCode, @Param("at") LocalDateTime at);
    @Query("SELECT DISTINCT role.code FROM UserCompanyRole assignment JOIN assignment.userCompany membership JOIN assignment.role role WHERE membership.user.id = :userId AND LOWER(membership.user.status) = 'active' AND membership.company.id = :companyId AND membership.deletedAt IS NULL AND membership.status = com.greenops.agent.domain.iam.MembershipStatus.ACTIVE AND (membership.effectiveFrom IS NULL OR membership.effectiveFrom <= :at) AND (membership.effectiveTo IS NULL OR membership.effectiveTo > :at) AND assignment.status = com.greenops.agent.domain.iam.Status.ACTIVE AND (assignment.effectiveFrom IS NULL OR assignment.effectiveFrom <= :at) AND (assignment.effectiveTo IS NULL OR assignment.effectiveTo > :at) AND role.status = com.greenops.agent.domain.iam.Status.ACTIVE AND role.deletedAt IS NULL AND (role.scope = com.greenops.agent.domain.iam.RoleScope.SYSTEM OR role.company.id = :companyId) ORDER BY role.code")
    List<String> findEffectiveRoleCodes(@Param("userId") UUID userId, @Param("companyId") UUID companyId, @Param("at") LocalDateTime at);
    @Query("SELECT DISTINCT membership FROM UserCompanyRole assignment JOIN assignment.userCompany membership JOIN FETCH membership.company JOIN assignment.role role WHERE membership.user.id = :userId AND membership.deletedAt IS NULL AND membership.status = com.greenops.agent.domain.iam.MembershipStatus.ACTIVE")
    List<UserCompany> findActiveCompanies(@Param("userId") UUID userId);
    @Query("SELECT DISTINCT membership.user.id FROM UserCompanyRole assignment JOIN assignment.userCompany membership WHERE assignment.role.id = :roleId AND assignment.status = com.greenops.agent.domain.iam.Status.ACTIVE")
    Set<UUID> findActiveUserIdsByRoleId(@Param("roleId") UUID roleId);
    @Query("SELECT DISTINCT membership.user.id, membership.company.id FROM UserCompanyRole assignment JOIN assignment.userCompany membership JOIN RolePermission grant ON grant.role = assignment.role WHERE grant.permission.id = :permissionId AND assignment.status = com.greenops.agent.domain.iam.Status.ACTIVE")
    List<Object[]> findActiveUserCompanyIdsByPermissionId(@Param("permissionId") UUID permissionId);
    @Query("SELECT DISTINCT membership.user.id, membership.company.id FROM UserCompanyRole assignment JOIN assignment.userCompany membership JOIN RolePermission grant ON grant.role = assignment.role JOIN grant.permission permission WHERE permission.module.id = :moduleId AND assignment.status = com.greenops.agent.domain.iam.Status.ACTIVE")
    List<Object[]> findActiveUserCompanyIdsByModuleId(@Param("moduleId") UUID moduleId);
    @Query("SELECT ucr FROM UserCompanyRole ucr WHERE ucr.userCompany.user.id = :userId AND ucr.userCompany.company.id = :companyId AND ucr.userCompany.deletedAt IS NULL")
    List<UserCompanyRole> findByTenantAndUser(@Param("companyId") UUID companyId, @Param("userId") UUID userId);

    @Query("SELECT DISTINCT permission.code AS code, permission.resource AS resource, permission.action AS action FROM UserCompanyRole assignment JOIN assignment.userCompany membership JOIN assignment.role role JOIN RolePermission rolePermission ON rolePermission.role = role JOIN rolePermission.permission permission WHERE membership.user.id = :userId AND LOWER(membership.user.status) = 'active' AND membership.company.id = :companyId AND membership.deletedAt IS NULL AND membership.status = com.greenops.agent.domain.iam.MembershipStatus.ACTIVE AND (membership.effectiveFrom IS NULL OR membership.effectiveFrom <= :at) AND (membership.effectiveTo IS NULL OR membership.effectiveTo > :at) AND assignment.status = com.greenops.agent.domain.iam.Status.ACTIVE AND (assignment.effectiveFrom IS NULL OR assignment.effectiveFrom <= :at) AND (assignment.effectiveTo IS NULL OR assignment.effectiveTo > :at) AND role.status = com.greenops.agent.domain.iam.Status.ACTIVE AND role.deletedAt IS NULL AND (role.scope = com.greenops.agent.domain.iam.RoleScope.SYSTEM OR role.company.id = :companyId) AND permission.status = com.greenops.agent.domain.iam.Status.ACTIVE AND permission.deletedAt IS NULL")
    Set<PermissionGrant> findEffectivePermissions(@Param("userId") UUID userId, @Param("companyId") UUID companyId, @Param("at") LocalDateTime at);

    @Query("SELECT DISTINCT permission.code AS code, permission.resource AS resource, permission.action AS action FROM UserCompanyRole assignment JOIN assignment.userCompany membership JOIN assignment.role role JOIN RolePermission rolePermission ON rolePermission.role = role JOIN rolePermission.permission permission WHERE membership.user.id = :userId AND LOWER(membership.user.status) = 'active' AND membership.company.id = :companyId AND membership.deletedAt IS NULL AND membership.status = com.greenops.agent.domain.iam.MembershipStatus.ACTIVE AND (membership.effectiveFrom IS NULL OR membership.effectiveFrom <= :at) AND (membership.effectiveTo IS NULL OR membership.effectiveTo > :at) AND assignment.status = com.greenops.agent.domain.iam.Status.ACTIVE AND (assignment.effectiveFrom IS NULL OR assignment.effectiveFrom <= :at) AND (assignment.effectiveTo IS NULL OR assignment.effectiveTo > :at) AND role.status = com.greenops.agent.domain.iam.Status.ACTIVE AND role.deletedAt IS NULL AND (role.scope = com.greenops.agent.domain.iam.RoleScope.SYSTEM OR role.company.id = :companyId) AND permission.code = :permissionCode AND permission.status = com.greenops.agent.domain.iam.Status.ACTIVE AND permission.deletedAt IS NULL")
    java.util.Optional<PermissionGrant> findEffectivePermission(@Param("userId") UUID userId, @Param("companyId") UUID companyId, @Param("permissionCode") String permissionCode, @Param("at") LocalDateTime at);
}
